# Generated by Django 6.0.6 on 2026-06-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_assets',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contacts',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='history',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills_tracking',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
